### ISSUE TITLE
Library does not work in projects with tslib < 2.1.0

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#423]
* Release number or git hash: 4.2.0-alpha.0
* Web browser version and OS: 

### Steps to reproduce

1. Use LineUp in any project with a "hard" dependency of `tslib` < 2.1.0, i.e. `"tslib": "~2.0.0"`

### Observed behavior
As soon as a ranking is instantiated, this error occurs and nothing works:
```
Uncaught (in promise) TypeError: Object(...) is not a function
    at new EngineRenderer (EngineRenderer.js:36)
    at new TaggleRenderer (TaggleRenderer.js:20)
    at new ARankingView (ARankingView.ts:166)
    at new EmbeddedRankingView (AEmbeddedRanking.ts:51)
    at RankingView.buildRanking (AEmbeddedRanking.ts:119)
    at new RankingView (RankingView.ts:65)
    at Jamborees.updateJamboree (Jamborees.ts:135)
    at Object.handler (Jamborees.ts:75)
    at AppState.ts:162
    at Array.map (<anonymous>)
```
This is because at this line, it uses the spread operator (...[asdf, ]), which is imported from tslib as `__spreadArray`. The problem is that __spreadArray only exists in tslib: 2.1.0 (https://github.com/microsoft/tslib/releases/tag/2.1.0), and it was previously called `__spreadArray*s*`. 

### Expected behavior

I suppose LineUp should work with libraries with `tslib < 2.1.0`. 

### (Possible) Solutions
Maybe there is a way of forcing `__spreadArrays` to be used while a transition/depreciation period is started, otherwise one could set the `"importHelpers": false` in `tsconfig.json`, which would directly put all those helper utilities in the code. This is of course bad regarding bundle-size, but better than not being able to use it at all. 

@sgratzl Do you have any input on this issue? LineUp is currently failing to work in several applications due to a `tslib` dependency lower than `2.1.0`, so is there a way to either remove/downgrade/make it compatible that I am missing?
